language: rust
rust: nightly

services: memcache
env: MEMCACHED__HOST=localhost

before_script:
  - memcached -p 2333 -d
  - memcached -p 2334 -d

script:
  - cargo build --verbose
  - cargo test --verbose -j1
