language: rust

rust:
  - stable
  - beta
  - nightly

services: memcache

env:
  - MEMCACHED__HOST=localhost

before_script:
  - memcached -p 12345 -d

script:
  - RUST_TEST_THREADS=1 RUST_BACKTRACE=1 cargo test
