language: rust
rust:
  - stable

services: memcache
env: MEMCACHED__HOST=localhost

before_script:
  - sudo apt-get install libmemcached-dev -y
  - memcached -p 2333 -d
  - memcached -p 2334 -d

script:
  - cargo build --verbose
  - cargo test --verbose -j1
