[package]
name = "memcache"
version = "0.0.10"
authors = ["asaka"]
repository = "https://github.com/aisk/rust-memcache"
readme = "README.md"
license = "MIT"
description = "memcached client for rust"
keywords = ["memcache", "memcached", "client", "driver"]

[dependencies.url]
git = "https://github.com/servo/rust-url"
