[package]
name = "memcache"
version = "0.0.14"
authors = ["asaka"]
repository = "https://github.com/aisk/rust-memcache"
readme = "README.md"
license = "MIT"
description = "memcached client for rust"
keywords = ["memcache", "memcached", "client", "driver"]

[dependencies]
